#!/bin/bash
set -euo pipefail
planetfilea=dach-latest.osm.pbf
styledir=/home/renderaccount/Mymapnik_openstreetmap-carto
cd /home/postgres/download
if [ -f $planetfilea ]
then
    rm $planetfilea
fi
# Aufbau der lokalen Postgis-Datenbank mit osm2psql
/usr/bin/wget https://download.geofabrik.de/europe/$planetfilea && /usr/bin/osm2pgsql --create -G --hstore-all --flat-nodes /home/postgres/download/flat.nodes -s -C 5000 --style $styledir/Server_Update/openstreetmap-carto_with_allotments.style --tag-transform-script $styledir/openstreetmap-carto.lua -d gis $planetfilea
# Initialisierung des inkrementellen Datenbankupdates
/usr/bin/osm2pgsql-replication init -d gis --server 'https://planet.openstreetmap.org/replication/minute'
# Aufbau der Lookup-Table für deutsche Baumarten
$styledir/Server_Update/create_lookup_table_for_tree_species.sh
# Löschen aller Caches
cd $styledir/Mymapproxy
/usr/bin/mapproxy-seed -s cleanup.yaml
# erstes inkrementelles Datenbankupdate
$styledir/Server_Update/update_osm_planet_dach_mapnik
# Neuaufbau des Caches
/usr/bin/mapproxy-seed -s seed_missing_tiles.yaml
