#!/bin/bash
set -euo pipefail
styledir=/home/renderaccount/Mymapnik_openstreetmap-carto
cd /home/postgres/download
# inkrementelles Datenbankupdate mit osm2psql-replication
/usr/bin/osm2pgsql-replication update -d gis --diff-file /home/postgres/download/changes.osc.gz --post-processing $styledir/Server_Update/run-expiry.sh -- --output flex --slim --style $styledir/openstreetmap-carto-flex.lua
# Wechsel ins mapproxy-Verzeichnis
cd $styledir/Mymapproxy
# Nachrendern der gelöschten Tiles in den seeding-Bereichen
if  [ $# -ge 1 ] && [ $1 == "-d" ]
then
 #   exec 2>/dev/null
    /usr/bin/mapproxy-seed -c 6 -f mapproxy.yaml -s seed_missing_tiles.yaml --duration 4m --continue --progress-file /var/cache/mapproxy/mapproxy_seed_progress    
else
    for (( zaehl=0 ; zaehl <5 ; zaehl++ ))
    do
	timeout 1800 /usr/bin/mapproxy-seed -c 3 -f mapproxy.yaml -s seed_missing_tiles.yaml  2> /dev/null && break
	echo "Wiederholungen mapproxy-seed: $zaehl"
	sleep 1
    done
fi    

